# This is the main Docker Compose file that defines all our services
# Docker Compose helps us run multiple containers together as a single application
# Version 3.8 is the latest stable version with good feature support

version: '3.8'

services:
  # Base image for all services
  base:
    build:
      context: .
      dockerfile: services/Dockerfile.base
    image: scamshield-base:dev
    profiles:
      - build-only

  # Frontend service - React application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - api-gateway

  # API Gateway service
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
    volumes:
      - ./services/api-gateway:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    depends_on:
      - auth-service
      - reporting-service

  # Authentication service
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile.dev
    ports:
      - '4001:4001'
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    depends_on:
      - postgres

  # Reporting service
  reporting-service:
    build:
      context: ./services/reporting-service
      dockerfile: Dockerfile.dev
    ports:
      - '4002:4002'
    volumes:
      - ./services/reporting-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    depends_on:
      - postgres

  # PostgreSQL Database
  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scamshield
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
