import type { Scam } from "@/models/scam"

// Mock scams data
export const mockScams: Scam[] = [
  {
    id: "scam-1",
    title: "Fake Banking Website",
    category: "phishing",
    severity: "high",
    description:
      "A sophisticated phishing attempt that mimics a major bank's website. Users are asked to enter their login credentials and personal information.",
    url: "https://fake-bank-website.com",
    date: "2024-05-01T10:30:00Z",
    reports: 156,
    status: "verified",
    userId: "user-1",
    contactInfo: "support@fake-bank-website.com",
    evidence: "The website has spelling errors and the domain was registered recently.",
  },
  {
    id: "scam-2",
    title: "Cryptocurrency Investment Scam",
    category: "investment",
    severity: "high",
    description:
      "A fraudulent investment scheme promising guaranteed high returns on cryptocurrency investments. Victims are asked to send cryptocurrency to a wallet address.",
    url: "https://crypto-quick-profits.com",
    date: "2024-04-28T14:15:00Z",
    reports: 89,
    status: "verified",
    userId: "user-2",
    contactInfo: "invest@crypto-quick-profits.com",
    evidence: "Multiple reports of lost funds and no ability to withdraw investments.",
  },
  {
    id: "scam-3",
    title: "Fake Job Offer",
    category: "employment",
    severity: "medium",
    description:
      "Scammers posing as recruiters from well-known companies offering high-paying remote jobs. They request personal information and sometimes payment for 'training materials'.",
    url: "",
    date: "2024-04-25T09:45:00Z",
    reports: 42,
    status: "verified",
    userId: "user-3",
    contactInfo: "careers@legitimate-company-careers.com",
    evidence: "The email domain doesn't match the official company domain. They ask for payment upfront.",
  },
  {
    id: "scam-4",
    title: "Tech Support Scam",
    category: "tech-support",
    severity: "medium",
    description:
      "Callers claiming to be from Microsoft or Apple technical support, saying your computer has a virus. They request remote access to your computer and payment for 'fixing' non-existent issues.",
    url: "",
    date: "2024-04-20T16:30:00Z",
    reports: 78,
    status: "verified",
    userId: "user-4",
    contactInfo: "+1-888-555-1234",
    evidence: "Legitimate tech companies don't make unsolicited calls about viruses or technical issues.",
  },
  {
    id: "scam-5",
    title: "Romance Scam",
    category: "romance",
    severity: "high",
    description:
      "Scammers create fake profiles on dating sites or social media, build relationships with victims, then ask for money for emergencies, travel expenses, or medical costs.",
    url: "",
    date: "2024-04-15T11:20:00Z",
    reports: 65,
    status: "verified",
    userId: "user-5",
    contactInfo: "Various dating apps and social media platforms",
    evidence: "The person refuses video calls and quickly asks for financial assistance.",
  },
  {
    id: "scam-6",
    title: "Fake Delivery Notification",
    category: "phishing",
    severity: "low",
    description:
      "SMS or email messages claiming to be from delivery companies like UPS or FedEx, saying you have a package waiting. Links lead to phishing sites that steal personal information.",
    url: "https://package-delivery-notification.com",
    date: "2024-04-10T13:45:00Z",
    reports: 112,
    status: "verified",
    userId: "user-6",
    contactInfo: "delivery@package-notification-center.com",
    evidence: "The URL doesn't match official delivery company domains. Messages contain spelling errors.",
  },
  {
    id: "scam-7",
    title: "Lottery/Prize Scam",
    category: "lottery",
    severity: "medium",
    description:
      "Notifications that you've won a lottery or prize you never entered, requiring payment of fees or taxes to claim your winnings.",
    url: "https://international-lottery-winners.com",
    date: "2024-04-05T10:10:00Z",
    reports: 54,
    status: "verified",
    userId: "user-7",
    contactInfo: "claims@international-lottery-winners.com",
    evidence: "Legitimate lotteries don't require upfront payment to claim winnings.",
  },
  {
    id: "scam-8",
    title: "Fake Charity",
    category: "charity",
    severity: "medium",
    description:
      "Fraudulent organizations posing as charities, especially after natural disasters or crises, collecting donations that never reach victims.",
    url: "https://disaster-relief-fund.org",
    date: "2024-04-01T09:30:00Z",
    reports: 37,
    status: "verified",
    userId: "user-8",
    contactInfo: "donate@disaster-relief-fund.org",
    evidence: "The charity isn't registered with official charity regulators. Website was created recently.",
  },
  {
    id: "scam-9",
    title: "Social Media Account Takeover",
    category: "social-media",
    severity: "medium",
    description:
      "Hackers gain access to social media accounts and message friends asking for money or gift cards, claiming to be in an emergency situation.",
    url: "",
    date: "2024-03-28T15:20:00Z",
    reports: 91,
    status: "verified",
    userId: "user-9",
    contactInfo: "Various social media platforms",
    evidence:
      "Sudden requests for financial help through social media messages, often with unusual language or urgency.",
  },
  {
    id: "scam-10",
    title: "Fake Shopping Website",
    category: "shopping",
    severity: "medium",
    description:
      "Fraudulent e-commerce websites offering high-demand products at suspiciously low prices. After payment, products never arrive or are counterfeit.",
    url: "https://designer-brands-discount.com",
    date: "2024-03-25T12:15:00Z",
    reports: 73,
    status: "verified",
    userId: "user-10",
    contactInfo: "support@designer-brands-discount.com",
    evidence: "Prices too good to be true. Limited contact information. Poor website design.",
  },
]
