FROM node:20-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY . .

# Expose port 4002
EXPOSE 4002

# Start the development server
CMD ["npm", "run", "dev"]

